### ISSUE TITLE
Add gallery for screenshots/videos

### ISSUE THREAD

**Issue by mre** [analysis-tools-dev/website-old#15]
For many tools we have more than one visual resource now. We should present them in a more appealing way. E.g. with a simple lightweight gallery or a lightbox.

**Comment by mre** [comment]
Example page: https://analysis-tools.dev/tool/deepcode
This shows the first video as the main media right now, but there is also a screenshot field which we don't use.

![image](https://user-images.githubusercontent.com/175809/94803318-69124380-03e9-11eb-95e1-3bd692388c3e.png)

I'd love to display thumbnails for the screenshot and the other video links, too.

**Comment by paulrrdiaz** [comment]
@mre Could I work on this?

**Comment by mre** [comment]
Sure, it's yours. Thanks for giving it a try. Let me know if you want to brainstorm on the design here. You can simply post a screenshot or so and I'll get back to you.

**Comment by paulrrdiaz** [comment]
@mre is this ok?

<img width="651" alt="Captura de Pantalla 2020-10-01 a la(s) 10 59 51 a  m" src="https://user-images.githubusercontent.com/1366028/94833907-542bb500-03d5-11eb-8f86-5b5f20aa8e93.png">

<img width="639" alt="Captura de Pantalla 2020-10-01 a la(s) 10 59 44 a  m" src="https://user-images.githubusercontent.com/1366028/94833889-4e35d400-03d5-11eb-9192-f565651f11a1.png">
