### ISSUE TITLE
Add number of stars next to each tool in overview

### ISSUE THREAD

**Issue by mre** [analysis-tools-dev/website-old#16]
The overview page for each tag should show the number of Github stars for each tool.
This information is already available in the GraphQL data in Gatsby. (Run the project and go to http://localhost:8000/__graphql). We would have to add the stars to the queried fields [here](https://github.com/analysis-tools-dev/website/blob/7a00a5a809fd30aa343ca9a786b3d60001f124b0/src/templates/tag.js#L170-L190) and show it on the page. (Maybe next to the title of the tool.
![image](https://user-images.githubusercontent.com/175809/94802650-59462f80-03e8-11eb-81a6-1b80861ba882.png)

**Comment by saraogipraveen** [comment]
Hi @mre, Want to take this up. Please assign

**Comment by saraogipraveen** [comment]
Is this already done? That yellow circle is the star count?

![image](https://user-images.githubusercontent.com/16433473/94802938-214de500-0406-11eb-8df2-c6243eacf44f.png)

**Comment by mre** [comment]
Sure @saraogipraveen. Assigned.

**Comment by mre** [comment]
Nope, that's the vote, which is not the number of Github stars (that's a different field).

**Comment by saraogipraveen** [comment]
@mre Issue can be closed now. Thanks

**Comment by mre** [comment]
Ah right. Thanks again for the contribution @saraogipraveen.
